version: '3'

services:
  database1:
    build:
       context: ./database/
    hostname: database1
    container_name: database1
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=*admin123
     - POSTGRES_DB=chatApp
    restart: always

  chat:
    build:
       context: .
    hostname: chatapplication
    container_name: chatapplication
    ports:
     - "80:8000"
    depends_on:
     - database1
    restart: always

  nginx:
    build:
       context: ./nginx/
    hostname: nginx
    container_name: nginx
    ports:
     - "8000:80"
    depends_on:
     - chat
    restart: always


